sqlite: &sqlite
  timeout: 5000
  pool: 5
  adapter: sqlite3

development:
  <<: *sqlite
  database: db/development.sqlite3

test:
  <<: *sqlite
  database: db/test.sqlite3

cucumber:
  <<: *sqlite
  database: db/cucumber.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: ssq-telethon_production
  pool: 5
  username: ssq-telethon
  password:
